name: Homebrew

on:
  release:
    types:
      - created

permissions:
  contents: read

jobs:
  homebrew:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@ac93e64636f67b85384f251de7359f58c5dee140 # main
        with:
          test-bot: false

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@ac93e64636f67b85384f251de7359f58c5dee140 # main

      - name: Bump packages
        uses: Homebrew/actions/bump-packages@ac93e64636f67b85384f251de7359f58c5dee140 # main
        with:
          token: ${{ secrets.COMMITTER_TOKEN }}
          formulae: repomix
